language: android
sudo: required
dist: trusty
services:
  - docker
before_install:
 - lsmod
 - dmesg
 - cat /proc/cpuinfo
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551
 - sudo apt-get update -qq
 - sudo apt-get install -y qemu-kvm libvirt-bin
 - cowsay hi
 - sudo virsh capabilities
